#!/usr/bin/env zsh

typeset -a colors; colors=(
  base1
  base2
  rose
  red
  orange
  yellow
  chartreuse
  green
  springgreen
  cyan
  azure
  blue
  violet
  magenta
  base3
  base4
)

echo "
┌────┬─────────────┬────┬─────────────┐
│  0 │ base1       │  1 │ base2       │
├────┼─────────────┼────┼─────────────┤
│  2 │ red         │  3 │ rose        │
├────┼─────────────┼────┼─────────────┤
│  4 │ yellow      │  5 │ orange      │
├────┼─────────────┼────┼─────────────┤
│  6 │ green       │  7 │ chartreuse  │
├────┼─────────────┼────┼─────────────┤
│  8 │ cyan        │  9 │ springgreen │
├────┼─────────────┼────┼─────────────┤
│ 11 │ blue        │ 12 │ azure       │
├────┼─────────────┼────┼─────────────┤
│ 12 │ magenta     │ 13 │ violet      │
├────┼─────────────┼────┼─────────────┤
│ 14 │ base3       │ 15 │ base4       │
└────┴─────────────┴────┴─────────────┘
"

echo "
Standard 8 colors + 8 bright colors
"

echo -n '    '
for color in {0..15}; do
  echo -n '  '${(r:3:: :)color}
done
echo

counter=0
for color in $colors; do
  echo -n "${(l:3:: :)counter} "
  counter=$((counter+1))
  for background in $colors; do
    echo -n -e $c[bg_$background]$c[$color] aY4 $c[reset]
  done
  echo
done

