#!/usr/bin/env zsh

echo -e "${c[base1]} COLOR BASE1 ${c[reset]} ${c[base2]} COLOR BASE2 ${c[reset]} ${c[base3]} COLOR BASE3 ${c[reset]} ${c[base4]} COLOR BASE4 ${c[reset]}"

echo

echo -e " ${c[red]}COLOR RED      ${c[rose]}COLOR LIGHT RED"
echo -e " ${c[yellow]}COLOR YELLOW   ${c[orange]}COLOR LIGHT YELLOW"
echo -e " ${c[green]}COLOR GREEN    ${c[chartreuse]}COLOR LIGHT GREEN"
echo -e " ${c[cyan]}COLOR CYAN     ${c[springgreen]}COLOR LIGHT CYAN"
echo -e " ${c[blue]}COLOR BLUE     ${c[azure]}COLOR LIGHT BLUE"
echo -e " ${c[magenta]}COLOR MAGENTA  ${c[violet]}COLOR LIGHT MAGENTA"

echo

echo -e "$c[rose] COLOR       ROSE ${c[reset]} ${c[red]} COLOR     RED ${c[reset]} ${c[orange]} COLOR      ORANGE ${c[reset]}"
echo
echo -e "                   ${c[yellow]} COLOR  YELLOW ${c[reset]}"
echo
echo -e "$c[chartreuse] COLOR CHARTREUSE ${c[reset]} ${c[green]} COLOR   GREEN ${c[reset]} ${c[springgreen]} COLOR SPRINGGREEN ${c[reset]}"
echo
echo -e "                   ${c[cyan]} COLOR    CYAN ${c[reset]}"
echo
echo -e "$c[azure] COLOR      AZURE ${c[reset]} ${c[blue]} COLOR    BLUE ${c[reset]} ${c[violet]} COLOR      VIOLET ${c[reset]}"
echo
echo -e "                   ${c[magenta]} COLOR MAGENTA ${c[reset]}"
