#!/usr/bin/env zsh


typeset -a colors; colors=(
  base1
  base2
  rose
  red
  orange
  yellow
  chartreuse
  green
  springgreen
  cyan
  dodgerblue
  blue
  violet
  magenta
  base3
  base4
)

echo "
┌────┬─────────────┬────┬─────────────┐
│  1 │ base1       │  2 │ base2       │
├────┼─────────────┼────┼─────────────┤
│  3 │ red         │  4 │ rose        │
├────┼─────────────┼────┼─────────────┤
│  5 │ yellow      │  6 │ orange      │
├────┼─────────────┼────┼─────────────┤
│  7 │ green       │  8 │ chartreuse  │
├────┼─────────────┼────┼─────────────┤
│  9 │ cyan        │ 10 │ springgreen │
├────┼─────────────┼────┼─────────────┤
│ 11 │ blue        │ 12 │ dodgerblue  │
├────┼─────────────┼────┼─────────────┤
│ 13 │ magenta     │ 14 │ violet      │
├────┼─────────────┼────┼─────────────┤
│ 15 │ base3       │ 16 │ base4       │
└────┴─────────────┴────┴─────────────┘
"

echo "
Standard 8 colors + 8 bright colors
"


echo -n '    '
for color in {1..16}; do
  echo -n '  '${(r:3:: :)color}
done
echo

counter=0
for color in $colors; do
  counter=$((counter+1))
  echo -n "${(l:3:: :)counter} "
  for background in $colors; do
  echo -n -e $c[bg_$background]$c[$color] aY4 $c[reset]
  done
  echo
done


echo "
Dimmed 8 colors + 8 bright colors
"


echo -n '    '
for color in {1..16}; do
  echo -n '  '${(r:3:: :)color}
done
echo

counter=0
for color in $colors; do
  counter=$((counter+1))
  echo -n "${(l:3:: :)counter} "
  for background in $colors; do
  echo -n -e $c[dim]$c[bg_$background]$c[$color] aY4 $c[reset]
  done
  echo
done
